from django.db import models

class Expediente(models.Model):
    letra= models.CharField(max_length=200, default = "a")
    numero=models.IntegerField()
    fecha_creacion = models.DateTimeField("Fecha de creacion")
    apellido = models.CharField(max_length=200, default = None)
    nombre = models.CharField(max_length=200, default = None)
    calle = models.CharField(max_length=200, default = None)
    entre = models.CharField(max_length=200, default = None)
    ncat = models.CharField(max_length=200, default = None)
    c = models.CharField(max_length=200, null=True)
    s = models.CharField(max_length=200, default = None)
    q = models.CharField(max_length=200, default = None)
    fr = models.CharField(max_length=200, default = None)
    mz = models.CharField(max_length=200, default = None)
    p = models.CharField(max_length=200, default = None)
    uf = models.CharField(max_length=200, default = None)
    numero_de_partida = models.IntegerField(default = None)
    numero_de_cuenta = models.IntegerField(default = None)
    solicita_servicio_de = models.CharField(max_length=200, default = None)
    realizo = models.CharField(max_length=200, default = None)
    construyo = models.CharField(max_length=200, default = None)
    medidor_marca = models.CharField(max_length=200, default = None)
    tipo = models.CharField(max_length=200, default = None)
    caudal = models.CharField(max_length=200, default = None)
    inspeciono = models.CharField(max_length=200, default = None)
    medidor_nº = models.IntegerField(default = None)
    estado = models.CharField(max_length=200, default = None)
    fecha_de_instalacion = models.DateTimeField("Fecha de instalacion", default = None)
    autorizo_tapado = models.CharField(max_length=200, default = None)
	
