# Generated by Django 2.2.5 on 2019-10-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expendiente', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creacion')),
                ('numero', models.IntegerField()),
                ('letra', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
            ],
        ),
    ]
