# Generated by Django 2.2.5 on 2019-10-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expendientes',
            new_name='Expendiente',
        ),
    ]
