# Generated by Django 2.2.5 on 2019-10-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_auto_20191015_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expendiente',
            new_name='Expediente',
        ),
    ]
