# Generated by Django 2.2.6 on 2019-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_auto_20191015_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='expendiente',
            new_name='Entre',
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='numero',
            new_name='Numero',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='letra',
        ),
        migrations.AddField(
            model_name='expediente',
            name='Letra',
            field=models.CharField(default='l', max_length=200),
            preserve_default=False,
        ),
    ]
