# Generated by Django 2.2.6 on 2019-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_auto_20191016_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='Numero',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='Entre',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='Letra',
        ),
        migrations.AddField(
            model_name='expediente',
            name='c',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='entre',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fr',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='letra',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='mz',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='ncat',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='p',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='q',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='s',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='uf',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='apellido',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nombre',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
